name: Ansible Playbook
on:
  push:
    branches: [master]

env:
  PJ_ACTOR: imanau
  PJ_REPO: ubuntu-setting-automatic

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone ${{ env.PJ_REPO }}
        uses: actions/checkout@v1
        with:
          repository: ${{ env.PJ_ACTOR }}/${{ env.PJ_REPO }}
          ref: refs/heads/master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Ubuntu image sudo installed
        run: docker-compose build

      - name: Docker-composer up
        run: docker-compose up -d

      - name: Ansible exec
        run: docker-compose exec -T ubuntu /usr/bin/ansible-playbook playbook.yml
